#!/bin/bash

# Demo script to showcase the NLP Pipeline Application
# This creates a visual demonstration of the application

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║         🎙️  NLP PIPELINE APPLICATION DEMO                     ║"
echo "║                                                                ║"
echo "║  Speech-to-Text → Summarization → Sinhala Translation         ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This demonstration shows the complete pipeline workflow:"
echo ""

# Step 1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📤 STEP 1: User uploads an audio file"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   File: presentation.mp3"
echo "   Size: 2.5 MB"
echo "   Duration: 45 seconds"
echo ""
sleep 2

# Step 2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎤 STEP 2: Speech-to-Text (Vosk)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Processing audio with Vosk model..."
echo "   Converting to WAV format... ✓"
echo "   Recognizing speech... ✓"
echo ""
echo "   📝 TRANSCRIPTION:"
echo "   ┌─────────────────────────────────────────────────────────────┐"
echo "   │ Artificial intelligence has revolutionized many industries  │"
echo "   │ in recent years. Machine learning algorithms are being used │"
echo "   │ in healthcare to diagnose diseases, in finance to predict   │"
echo "   │ market trends, and in transportation to develop autonomous  │"
echo "   │ vehicles. Researchers predict that AI will continue to grow │"
echo "   │ and impact society in profound ways. Companies are investing│"
echo "   │ billions of dollars in AI development. The technology       │"
echo "   │ promises both opportunities and challenges for the future.  │"
echo "   └─────────────────────────────────────────────────────────────┘"
echo ""
sleep 3

# Step 3
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ STEP 3: Text Summarization (TF-IDF)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Analyzing text with TF-IDF algorithm..."
echo "   Calculating term frequencies... ✓"
echo "   Computing sentence scores... ✓"
echo "   Selecting top 3 sentences... ✓"
echo ""
echo "   📊 SUMMARY:"
echo "   ┌─────────────────────────────────────────────────────────────┐"
echo "   │ Artificial intelligence has revolutionized many industries  │"
echo "   │ in recent years. Machine learning algorithms are being used │"
echo "   │ in healthcare, finance, and transportation. The technology  │"
echo "   │ promises both opportunities and challenges for the future.  │"
echo "   └─────────────────────────────────────────────────────────────┘"
echo ""
sleep 3

# Step 4
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 STEP 4: English-to-Sinhala Translation (MT5)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Loading MT5 translation model..."
echo "   Tokenizing text... ✓"
echo "   Generating translation... ✓"
echo ""
echo "   🇱🇰 SINHALA TRANSLATION:"
echo "   ┌─────────────────────────────────────────────────────────────┐"
echo "   │ කෘතිම බුද්ධිය මෑත වසරවලදී බොහෝ කර්මාන්ත විප්ලවීය        │"
echo "   │ වෙනසක් කර ඇත. යන්ත්‍ර ඉගෙනුම් ඇල්ගොරිතම සෞඛ්‍ය,         │"
echo "   │ මූල්‍ය සහ ප්‍රවාහනයේ භාවිතා වේ. තාක්ෂණය අනාගතය සඳහා       │"
echo "   │ අවස්ථා සහ අභියෝග දෙකම පොරොන්දු වේ.                         │"
echo "   └─────────────────────────────────────────────────────────────┘"
echo ""
sleep 3

# Final
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ PROCESSING COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Total Processing Time: ~12 seconds"
echo ""
echo "   📊 RESULTS SUMMARY:"
echo "   • Transcription: 64 words, 426 characters"
echo "   • Summary: 32 words, 214 characters (50% reduction)"
echo "   • Translation: Successfully converted to Sinhala"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 KEY FEATURES:"
echo ""
echo "   ✓ Automatic audio format conversion"
echo "   ✓ High-quality speech recognition"
echo "   ✓ Intelligent extractive summarization"
echo "   ✓ Neural machine translation"
echo "   ✓ Modern web interface"
echo "   ✓ Real-time progress tracking"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 TO START THE APPLICATION:"
echo ""
echo "   ./start.sh"
echo ""
echo "   Then open: http://localhost:8000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "   README.md          - Main documentation"
echo "   QUICKSTART.md      - Quick start guide"
echo "   USER_GUIDE.md      - Detailed usage guide"
echo "   ARCHITECTURE.md    - Technical architecture"
echo "   DEPLOYMENT.md      - Deployment guide"
echo "   PROJECT_SUMMARY.md - Project overview"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Thank you for using the NLP Pipeline Application! 🎉"
echo ""
